export const enum FeatureName {
  TimeInterval = "asteroidsTimeInterval",
  AsteroidDetail = "asteroidDetails",
  DailyPicture = "dailyPictureData",
  Satellites = "satellitesData",
  MediaDetail = "mediaDetails",
  Asteroids = "asteroidsData",
  Modal = "canDisplayModal",
  Sheet = "canDisplaySheet",
  RateLimit = "rateLimits",
  Audios = "nasaAudios",
  Videos = "nasaVideos",
  Images = "nasaImages",
  Theme = "colorTheme",
  Errors = "errors",
  Search = "search",
  Media = "media",
  Page = "page",
}
