export enum TestKey {
  DailyPictureScreenIcon = "dailyPictureScreenIcon",
  SatellitesScreenIcon = "satellitesScreenIcon",
  AsteroidsScreenIcon = "asteroidsScreenIcon",
  GalleryScreenIcon = "galleryScreenIcon",
  AsteroidsExplore = "asteroidsExplore",
  AstroidDetails = "asteroidDetails",
  ExploreButton = "exploreButton",
  DailyPicture = "dailyPicture",
  NoAsteroids = "noAsteroids",
  RetryButton = "retryButton",
  DangerIcon = "dangerIcon",
  Satellites = "satellites",
  SearchIcon = "searchIcon",
  Asteroids = "asteroids",
  SafeIcon = "safeIcon",
  Carousel = "carousel",
  Gallery = "gallery",
  NoMedia = "noMedia",
  Spinner = "spinner",
  Images = "images",
  Videos = "videos",
  Audios = "audios",
}
